import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# 1. Read the data generated by the C++ program
print("Reading C++ simulation results...")
df = pd.read_csv("decay_results.csv")

t_sim = df["Time"]
N_sim = df["Particles"]

# 2. Calculate the Theoretical Curve (Physics Prediction)
# Formula: N(t) = N0 * e^(-lambda * t)
N0 = 1000       
lmbda =0.1     
t_theory = np.linspace(0, max(t_sim), 200)
N_theory = N0 * np.exp(-lmbda * t_theory)

# 3. Create the Plot
plt.figure(figsize=(10, 6))

# Plot the Simulation (Scatter points)
plt.scatter(t_sim, N_sim, color='red', s=10, label='C++ Monte Carlo Simulation', zorder=2)

# Plot the Theory (Smooth line)
plt.plot(t_theory, N_theory, color='blue', linestyle='--', linewidth=2, label='Theoretical Prediction ($N_0 e^{-\lambda t}$)', zorder=1)

plt.title("Radioactive Decay: Monte Carlo vs Theory", fontsize=15)
plt.xlabel("Time Step", fontsize=12)
plt.ylabel("Remaining Particles", fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)

# 5. Save the image
plt.savefig("decay_plot.png")
print("'decay_plot.png'")